version: "3.4"

services:
  whose-turn-is-it-webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: whose-turn-is-it-webapp
    container_name: whose-turn-is-it-webapp
    command: "npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/app

      # create an empty directory at `/app/node_modules` instead of using the previously
      # mounted `./webapp/node_modules` directory, so the host's `node_modules` ownership
      # doesn't pass to the container's user
      - /app/node_modules

  qr:
    build:
      context: ./qr
      dockerfile: Dockerfile
    image: qr
    container_name: qr
    volumes:
      - ./qr:/app
